# CustomArcheology by @rzt1020
#
# Read the Wiki here: customarcheology.superiormc.cn
# Purchase the plugin, and you can get free texture expansion pack with 5 tools, 6 blocks included!

log-generated-block: false

config-files:
  generate-default-files: true
  language: en_US
  minecraft-locate-file:
    # After enable, we will autoload Minecraft locate file when we need know an item's locate name.
    # It will make server little lag when loading this file because this file is very large.
    enabled: true
    generate-new-one: false
    file: 'zh_cn.json'

auto-copy-resourcepack:
  enabled: true
  # If you are using Oraxen, please change this to Oraxen.
  # Other plugins is OK, you just need put correct path in path option.
  plugin: "ItemsAdder"
  # If you are using Oraxen, please change this to "/pack/assets".
  path: "/contents/customarcheology/resourcepack/"

database:
  use-mysql: false
  mysql:
    host: localhost
    port: 3306
    user: root
    password: root
    database: minecraft

settings:
  # Support value: UUID or RANDOM
  block-save: UUID
  start-custom-model-data:
    block: 10000
    tool: 10000
  visible-distance: 8
  item-scale: 0.5
  block-scale: 0.25
  hook:
    betterstructures: true